---
- name: Install netbox in docker
  hosts: localhost
  become: true
  vars:
    netbox_ssl_cert_bundle: /etc/ssl/private/localhost+2.pem
    netbox_ssl_cert_key: /etc/ssl/private/localhost+2-key.pem
    netbox_use_caddy: true
    netbox_plugins:
      - name: netbox_prometheus_sd
        src: https://github.com/FlxPeters/netbox-plugin-prometheus-sd.git
        version: v1.1.1
  roles:
    - jsenecal.netbox_docker
